classDiagram

class Book {
    -String title
    -String author
    -Date publishedDate
    -boolean isAvailable

    +String getTitle()
    +String getAuthor()
    +Date getPublishedDate()
    +boolean checkAvailable()
}